### PR TITLE
SDAP-55

### PR DESCRIPTION
**Pull request by quintinali**
clean up weblog module
(1) remove seqential log processing code
(2) fix bugs of clickstream extration

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by lewismc** [comment]
+1 @quintinali please push to master branch thank you. Good job.

**Comment by lewismc** [comment]
@quintinali can you please resolve conflict then merge, thank you.

**Comment by quintinali** [comment]
@lewismc The last commits said that the master branch is merged into SDAP-55. Is there something wrong?  I thought the pull request should merge SDAP-55 into the master branch. Thanks.

**Comment by lewismc** [comment]
This looks fine. +1 for merge, please go ahead and do that. Thanks.

**Comment by quintinali** [comment]
@lewismc I can't find the merge button on this page. Here is the snapshot:
image

**Comment by lewismc** [comment]
@quintinali you need to follow the instructions I posted to the dev@ mailing list before Christmas time. 

https://gitbox.apache.org/setup/

Let me know if you have any issues, thanks.

**Comment by lewismc** [comment]
@quintinali thank you for the patch, I went ahead and merged into master branch. Please let me know if you have any issues with setting up Github integration.

**Comment by quintinali** [comment]
@lewismc Thank you. I took multiple flights in the past two days and it is strange that my computer can’t connect to the WiFi at the airport. Thus I didn’t merge the branch on time. I tried to merge my Apache account and Github account through the link you sent to me and has finished the first two steps. I will let you know if any issue.

**Pull request merged**
