### PR TITLE
Fixed missing sweetAll.owl, typos and made minor improvements.

### PR DESCRIPTION
**Pull request by kamaci**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by lewismc** [comment]
@kamaci thank you for the patch. Can you please log issues in JIRA if you plan to contribute more? I appreciate it. That way we can track it.

**Comment by kamaci** [comment]
> @kamaci thank you for the patch. Can you please log issues in JIRA if you plan to contribute more? I appreciate it. That way we can track it.

Sure, I will 👍

**Comment by kamaci** [comment]
Fixes SDAP-177

**Pull request merged**
