### PR TITLE
SDAP-120 Error trying to ingest logs

### PR DESCRIPTION
**Pull request by fgreg**
The Apache logs no longer contain referrer and agent. Here is an example log line from the latest access logs:

    String testLogLine = "198.118.243.84 - - [31/Dec/2017:23:59:20 +0000] \"GET /events?page=12&amp%25252525252525252525252525252525252525253Bsort=asc&order=field_location&sort=desc HTTP/1.1\" 200 86173";

This does not match the pattern https://github.com/apache/incubator-sdap-mudrod/blob/faac228e88ebdb9fbd8e134f8550d5dc16738a71/core/src/main/java/org/apache/sdap/mudrod/weblog/structure/log/ApacheAccessLog.java#L62

because of the last 2 groups at the end of that pattern:

> "((?:[^"]|")+)" "([^"]+)"

Those last two groups are used for Referer and browser/user agent and I think are quite important for the log processing.

So far I've just written a unit test that fails with the example log line. I need help from @lewismc or @quintinali to determine how this should be fixed.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by lewismc** [comment]
Hi @fgreg for some reason Chris Finch and the team who manage the HTTPD server which generates the logs have changed the logging format from the combined log format to the common log format (https://httpd.apache.org/docs/current/logs.html#accesslog), this is a regression in my opinion so we need to take it up with them. I'll write Chris an email to find out why this has happened.

**Comment by lewismc** [comment]
@fgreg I've reached out to Chris, hopefully we get an answer reasonably soon and they can revert to use combined log format. Thanks
For the time being, we will need to use older monthly logs which were written in the combined log format.

**Comment by lewismc** [comment]
The regression happened during the move to HTTPS, which was April of 2017 (wow that was a long time ago). You can see from the logs available at ftp://podaac.jpl.nasa.gov/misc/outgoing/cjf/mudrod/2017/04/, that the WWW.* artifacts contain the combined log format, whereas the WWWssl logs do not! Example are below
 
Combined Log Format (Pre HTTPS/SSL Migration < April 2017)
```
198.118.243.84 - - [29/Apr/2017:00:00:49 +0000] "GET /announcements/2016-08-29_RapidScat_Data_Loss_from_Power_Outage HTTP/1.1" 302 274 "-" "gsa-crawler-earthdata (Enterprise; T5-ACQ4X8DLW7SKC; earthdata-sa@lists.nasa.gov,srinivasa.s.tummala@nasa.gov)"
```

Common Log Format (Post HTTPS/SSL Migration > April 2017)
```
131.161.10.197 - - [29/Apr/2017:00:00:20 +0000] "GET /datasetlist?ids=Sensor:DataFormat:Collections:Measurement&values=SMAP_RADIOMETER:HDF5:Aquarius-CAP:Salinity%252525252525252FDensity HTTP/1.1" 200 86612
```
You can clearly see the absence of the Referrer and User Agent in the Common Log Format.
 
Addressing this regression is a priority and it does not have an adverse impact on the Webserver performance as this information is already cached in the WebServer we simply do not log it anymore. I'm working to get this fixed.

**Comment by lewismc** [comment]
Hi @fgreg this issue has been resolved, we've addressed the regression in the HTTPD server producing the logs which now means logs are written int he combined log format.
New logs can be found at
ftp://podaac.jpl.nasa.gov/misc/outgoing/cjf/mudrod/2018/07/
...where the logs to be used are everything APART from the artifact containing **old** in the name. From now on, all servers will be logging in the combined log format.
I'm going to close this off for the time being, please re-open if you feel this is an issue.

**Comment by lewismc** [comment]
Just checked the PR properly and it is it a test!!!! Merged thank you @fgreg

**Pull request merged**
