### PR TITLE
SDAP-35 Overhaul MUDROD configuration

### PR DESCRIPTION
**Pull request by Yongyao**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by Yongyao** [comment]
@lewismc Please check this new PR out. All change requests have been made except for the upper case one.

**Review by lewismc — APPROVED** [review]
+1 to commit, please merge into master branch and close the corresponding JIRA ticket.
@Yongyao please be careful when formatting files. There are several file e.g. core/src/main/java/org/apache/sdap/mudrod/metadata/structure/PODAACMetadata.java which you have used 4 space indents. This is not the formatting we are using for the Java code in MUDROD so please make sure that you use 2 space formatting.
This is a signifiant improvement of the configuration loading so thank you for the patch.

**Comment by Yongyao** [comment]
@lewismc Format changed. I don't have permission to merge the PR. I saw you sent out some apache roster a while ago. Is this related to that?

**Comment by lewismc** [comment]
> I don't have permission to merge the PR. I saw you sent out some apache roster a while ago. Is this related to that?

See https://gitbox.apache.org/setup/

**Comment by Yongyao** [comment]
@lewismc It turns out I don't have an apahe id (https://id.apache.org/). I have access to https://issues.apache.org, but it looks like they are not the same thing. 
As for the roaster email, the website ( https://whimsy.apache.org/roster/ppmc/sdap) is asking for my pw which I don't have either.

**Comment by lewismc** [comment]
@Yongyao in id.apache.org you will see a reset password option. Use it.

**Comment by Yongyao** [comment]
Thanks. Got it.

**Pull request merged**
