### PR TITLE
SDAP-182 Localization and charset definitions are done.

### PR DESCRIPTION
**Pull request by kamaci**

### CODE REVIEW

**Comment by lewismc** [comment]
@kamaci is there an advantage of using `Locale.ROOT`? Over say `Locate.getDefault()...`?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by kamaci** [comment]
About [Locale.ROOT:](https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#ROOT
)
> Useful constant for the root locale. The root locale is the locale whose language, country, and variant are empty ("") strings. This is regarded as the base locale of all locales, and is used as the language/country neutral locale for the locale sensitive operations.

About `Locale.getDefault()`, it may cause weird problems i.e.: https://issues.apache.org/jira/browse/HADOOP-11507

**Comment by kamaci** [comment]
On the other hand, it may result in weird situations if default locale of the machine which runs the code is any other Locale than English i.e.: https://github.com/apache/incubator-druid/pull/7120

**Comment by lewismc** [comment]
@kamaci do you want to update this PR?

**Comment by kamaci** [comment]
@lewismc I've updated my PR. 

By the way, I can replace `Locale.ROOT` with `Locale.ENGLISH`: https://stackoverflow.com/questions/10336730/which-locale-should-i-specify-when-i-call-string-tolowercase ?

**Comment by lewismc** [comment]
@kamaci yes if you could replace with Locale.ENGLISH I think it would be preferred at this point.

**Comment by kamaci** [comment]
> @kamaci yes if you could replace with Locale.ENGLISH I think it would be preferred at this point.

@lewismc I've updated my PR.

**Pull request merged**
